const GAMES = [
  {
    id: "subway-surfers",
    title: "Subway Surfers",
    slug: "subway-surfers",
    category: ["action", "endless-runner"],
    thumbnail: "https://img.gamedistribution.com/a0f2840acfce4dab824a3a9624f0a815-512x512.jpeg",
    embedUrl: "https://html5.gamedistribution.com/a0f2840acfce4dab824a3a9624f0a815/",
    status: "live",
    madeInAfrica: false,
    featured: true,
    description: "Run, dodge and dash through the subway while being chased by the inspector. One of the most played mobile games ever."
  },
  {
    id: "temple-run-2",
    title: "Temple Run 2",
    slug: "temple-run-2",
    category: ["action", "endless-runner"],
    thumbnail: "https://img.gamedistribution.com/6a66f0a2d65f4ca3b4864b823e2a7b3d-512x512.jpeg",
    embedUrl: "https://html5.gamedistribution.com/6a66f0a2d65f4ca3b4864b823e2a7b3d/",
    status: "live",
    madeInAfrica: false,
    featured: true,
    description: "Run, turn, jump and slide to escape the demon monkeys through jungle ruins."
  },
  {
    id: "snow-rider-3d",
    title: "Snow Rider 3D",
    slug: "snow-rider-3d",
    category: ["racing", "action"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Snow+Rider+3D",
    embedUrl: "https://html5.gamedistribution.com/b8f73f2b7f7b4b0e9f5d5f5f5f5f5f5f/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: true,
    description: "Sled down snowy mountains dodging trees and obstacles. Beautiful 3D graphics."
  },
  {
    id: "drift-boss",
    title: "Drift Boss",
    slug: "drift-boss",
    category: ["racing"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Drift+Boss",
    embedUrl: "https://html5.gamedistribution.com/driftboss/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: true,
    description: "One button drifting game. Time your turns perfectly and go as far as possible."
  },
  {
    id: "basketball-stars",
    title: "Basketball Stars",
    slug: "basketball-stars",
    category: ["sports"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Basketball+Stars",
    embedUrl: "https://html5.gamedistribution.com/basketballstars/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: true,
    description: "1v1 basketball against real opponents. Show off your skills and win tournaments."
  },
  {
    id: "football-legends",
    title: "Football Legends",
    slug: "football-legends",
    category: ["sports"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Football+Legends",
    embedUrl: "https://html5.gamedistribution.com/footballlegends/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: true,
    description: "Play as your favourite football legends in this fun 1v1 or 2v2 football game."
  },
  {
    id: "2048",
    title: "2048",
    slug: "2048",
    category: ["puzzle"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=2048",
    embedUrl: "https://play.famobi.com/2048",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Slide tiles and combine numbers to reach 2048. Simple to learn, hard to master."
  },
  {
    id: "moto-x3m",
    title: "Moto X3M",
    slug: "moto-x3m",
    category: ["racing", "action"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Moto+X3M",
    embedUrl: "https://html5.gamedistribution.com/rvvASMiM/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Race through insane obstacle courses on your bike without crashing."
  },
  {
    id: "stickman-hook",
    title: "Stickman Hook",
    slug: "stickman-hook",
    category: ["action", "arcade"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Stickman+Hook",
    embedUrl: "https://html5.gamedistribution.com/stickman-hook/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Swing through levels using a grappling hook. Addictive one-tap gameplay."
  },
  {
    id: "mahjong-classic",
    title: "Mahjong Classic",
    slug: "mahjong-classic",
    category: ["puzzle"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Mahjong+Classic",
    embedUrl: "https://html5.gamedistribution.com/mahjongclassic/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Match pairs of tiles and clear the board. The classic Mahjong experience."
  },
  {
    id: "cut-the-rope",
    title: "Cut the Rope",
    slug: "cut-the-rope",
    category: ["puzzle"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Cut+the+Rope",
    embedUrl: "https://html5.gamedistribution.com/cuttherope/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Cut ropes to feed candy to Om Nom. Hundreds of fun physics puzzles."
  },
  {
    id: "traffic-jam-3d",
    title: "Traffic Jam 3D",
    slug: "traffic-jam-3d",
    category: ["puzzle", "racing"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Traffic+Jam+3D",
    embedUrl: "https://html5.gamedistribution.com/trafficjam3d/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Slide cars out of the traffic jam. A satisfying puzzle game."
  },
  {
    id: "brain-test",
    title: "Brain Test",
    slug: "brain-test",
    category: ["puzzle"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Brain+Test",
    embedUrl: "https://html5.gamedistribution.com/braintest/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Tricky brain teasers that will challenge everything you think you know."
  },
  {
    id: "table-tennis",
    title: "Table Tennis World Tour",
    slug: "table-tennis",
    category: ["sports"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Table+Tennis",
    embedUrl: "https://html5.gamedistribution.com/tabletennisworldtour/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Compete in table tennis tournaments across the world. Fast reflexes required."
  },
  {
    id: "bubble-shooter",
    title: "Bubble Shooter",
    slug: "bubble-shooter",
    category: ["puzzle", "arcade"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Bubble+Shooter",
    embedUrl: "https://html5.gamedistribution.com/bubble-shooter/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Aim and shoot colored bubbles to match and pop groups of three or more."
  },
  {
    id: "geometry-dash",
    title: "Geometry Dash Lite",
    slug: "geometry-dash",
    category: ["action", "arcade"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Geometry+Dash",
    embedUrl: "https://html5.gamedistribution.com/geometrydashlite/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Jump and fly your way through danger in this rhythm-based action platformer."
  },
  {
    id: "road-rush",
    title: "Road Rush Cars",
    slug: "road-rush",
    category: ["racing", "action"],
    thumbnail: "https://placehold.co/512x512/0d1117/f5a623?text=Road+Rush+Cars",
    embedUrl: "https://html5.gamedistribution.com/roadrushcars/",
    status: "coming-soon",
    madeInAfrica: false,
    featured: false,
    description: "Dodge traffic at high speed on a busy highway. How far can you go?"
  },
  {
    id: "savanna-runner",
    title: "Savanna Runner",
    slug: "savanna-runner",
    category: ["action", "endless-runner"],
    thumbnail: "https://placehold.co/512x512/3a2800/f5a623?text=Savanna+Runner",
    embedUrl: "",
    status: "coming-soon",
    madeInAfrica: true,
    featured: true,
    description: "Run across the African savanna, dodge animals and collect gems. Coming soon."
  }
];